# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pclab',
                'doc_host': 'https://JohnRomanelis.github.io',
                'git_url': 'https://github.com/JohnRomanelis/pclab',
                'lib_path': 'pclab'},
  'syms': {'pclab.core': {'pclab.core.foo': ('core.html#foo', 'pclab/core.py')}}}
