# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_transforms.ipynb.

# %% auto 0
__all__ = ['FirstKPointsKeep', 'RandomPointKeep', 'UnitSphereNormalization', 'RandomShuffle', 'AnisotropicScale',
           'RandomPointDropout', 'ToTensor']

# %% ../nbs/00_transforms.ipynb 3
import numpy as np
import torch

# %% ../nbs/00_transforms.ipynb 4
class FirstKPointsKeep:
    "Keep a subset of the original pointcloud containing the K first points"
    def __init__(self, num_points:int): # number of points to keep
        self.num_points = num_points

    def __call__(self, x):
        return x[:self.num_points, :]

# %% ../nbs/00_transforms.ipynb 6
class RandomPointKeep:
    "Keep a random subset of points from the original pointcloud"
    def __init__(self, num_points:int): # number of points to keep
        self.num_points = num_points
        
    def __call__(self, x):
        np.random.shuffle(x)
        return x[:self.num_points, :]

# %% ../nbs/00_transforms.ipynb 8
class UnitSphereNormalization:
    "Normalizes the coordinates of the point cloud, so that all points are inside the unit sphere"

    def __call__(self, pc):
        centroid = np.mean(pc, axis=0)
        pc = pc - centroid
        m = np.max(np.sqrt(np.sum(pc**2, axis=1)))
        pc = pc / m
        return pc

# %% ../nbs/00_transforms.ipynb 9
class RandomShuffle:
    "Shuffles the order of the points inside the point cloud"
    def __call__(self, pc):
        np.random.shuffle(pc)
        return pc

# %% ../nbs/00_transforms.ipynb 10
class AnisotropicScale:
    "Performs a random anisotropic scaling of the point cloud"
    def __call__(self, pc):
        xyz1 = np.random.uniform(low=2./3., high=3./2., size=[3])
        xyz2 = np.random.uniform(low=-0.2, high=0.2, size=[3])
        pointcloud = pc
        translated_pointcloud = pointcloud * xyz1 + xyz2
        return translated_pointcloud.astype(np.float32)

# %% ../nbs/00_transforms.ipynb 11
class RandomPointDropout:
    "Randomly removes a subset of the point cloud. To keep the shape of the point cloud constant we set all the removed points to have the same coordinates."
    def __init__(self, max_dropout_ratio = 0.875):
        self.max_dropout_ratio = max_dropout_ratio
        
    def __call__(self, pc):  
        dropout_ratio = np.random.random() * self.max_dropout_ratio # 0 ~ 0.875
        drop_idx = np.where(np.random.random((pc.shape[0])) <= dropout_ratio)[0]

        if len(drop_idx) > 0:
            pc[drop_idx,:] = pc[0,:] # set to the first point

        return pc

# %% ../nbs/00_transforms.ipynb 12
class ToTensor:
    "Turns a numpy array to a torch tensor"
    def __call__(self, pc):
        pc = torch.from_numpy(pc)
        return pc

