# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['pc_to_o3d', 'quick_vis']

# %% ../nbs/00_utils.ipynb 2
import numpy as np
import torch
import open3d as o3d

# %% ../nbs/00_utils.ipynb 3
def pc_to_o3d(pc): # point cloud as np.array or torch.tensor
    "turn a point cloud, represented as a np.array or torch.tensor to an [Open3D.geometry.PointCloud](http://www.open3d.org/docs/0.16.0/python_api/open3d.geometry.PointCloud.html)"
    pc = o3d.geometry.PointCloud(
            o3d.utility.Vector3dVector(pc)
    )
    return pc

# %% ../nbs/00_utils.ipynb 4
def quick_vis(pc): # point cloud as np.array or torch.tensor
    pc = pc_to_o3d(pc)
    o3d.visualization.draw_geometries([pc])
